### ISSUE TITLE
Creating a test environment with QEMU and KVM - learning ansible 2 

### ISSUE THREAD

**Issue by tziokioa** [PacktPublishing/Learning-Ansible-2-Second-Edition#1]
Following the steps for Creating a test environment with QEMU and
KVM I am getting an error for the section from page 15:
virt-install --name CentOS_1 \
--ram 2048 \
--disk centos_1.qcow2 \
--vcpus 2 \
--os-variant fedora21 \
--connect qemu:///system \
--network bridge:br0,model=virtio \
--cdrom centos_1.iso \
--boot hd

the issue is with bridge:br0 
at what point did we configure such a bridge? it is not mentioned in the book.
could you advise?

**Comment by deepesh-packt** [comment]
Please reopen if the issue still persists.
